services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_pw
      MYSQL_DATABASE: online-learning
      MYSQL_USER: user
      MYSQL_PASSWORD: user_pw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - go-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_pw
    ports:
      - "8081:80"
    networks:
      - go-network

  golang-server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
    - .env
    ports:
      - "8080:8080"
    networks:
      - go-network
    depends_on:
      - mysql
  nginx:
    image: nginx:latest
    container_name: nginx-container
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/nginx/ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - golang-server
    networks:
      - go-network

volumes:
  mysql_data:

networks:
  go-network:
    driver: bridge