basePath: /api/v1
definitions:
  models.AccessTokenResponse:
    properties:
      accessToken:
        type: string
      expiresIn:
        type: integer
    required:
    - accessToken
    - expiresIn
    type: object
  models.ClassWithSubjects:
    properties:
      classId:
        type: integer
      className:
        type: string
      count:
        type: integer
      subjects:
        items:
          $ref: '#/definitions/models.SubjectId'
        type: array
    required:
    - classId
    - className
    - count
    - subjects
    type: object
  models.Contact:
    properties:
      content:
        type: string
      email:
        type: string
      fullName:
        type: string
      title:
        type: string
    required:
    - content
    - email
    - fullName
    - title
    type: object
  models.CreateUserRequest:
    properties:
      avatar:
        type: string
      dateOfBirth:
        type: string
      email:
        type: string
      fullName:
        type: string
      gender:
        $ref: '#/definitions/models.UserGender'
      password:
        minLength: 6
        type: string
      role:
        $ref: '#/definitions/models.UserRole'
      username:
        type: string
    required:
    - avatar
    - dateOfBirth
    - email
    - fullName
    - gender
    - password
    - username
    type: object
  models.Error:
    properties:
      error:
        type: string
    required:
    - error
    type: object
  models.ForgotPasswordRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  models.LoginRequest:
    properties:
      identifier:
        type: string
      password:
        type: string
    required:
    - identifier
    - password
    type: object
  models.LoginResponse:
    properties:
      accessToken:
        type: string
      expiresIn:
        type: integer
      message:
        type: string
      user:
        $ref: '#/definitions/models.UserDetail'
    required:
    - accessToken
    - expiresIn
    - message
    - user
    type: object
  models.Message:
    properties:
      message:
        type: string
    required:
    - message
    type: object
  models.PagingInfo:
    properties:
      limit:
        type: integer
      page:
        type: integer
      totalCount:
        type: integer
    required:
    - limit
    - page
    - totalCount
    type: object
  models.PasswordUpdateRequest:
    properties:
      currentPassword:
        minLength: 6
        type: string
      newPassword:
        minLength: 6
        type: string
    required:
    - currentPassword
    - newPassword
    type: object
  models.ResetPasswordRequest:
    properties:
      password:
        minLength: 6
        type: string
    required:
    - password
    type: object
  models.SubjectId:
    properties:
      count:
        type: integer
      subjectId:
        type: integer
      subjectName:
        type: string
    required:
    - count
    - subjectId
    - subjectName
    type: object
  models.UpdateUserResponse:
    properties:
      message:
        type: string
      user:
        $ref: '#/definitions/models.UserDetail'
    required:
    - message
    - user
    type: object
  models.UserDetail:
    properties:
      avatar:
        type: string
      createdAt:
        type: string
      dateOfBirth:
        type: string
      email:
        type: string
      fullName:
        type: string
      gender:
        $ref: '#/definitions/models.UserGender'
      id:
        type: integer
      role:
        $ref: '#/definitions/models.UserRole'
      username:
        type: string
    required:
    - avatar
    - createdAt
    - dateOfBirth
    - email
    - fullName
    - gender
    - id
    - role
    - username
    type: object
  models.UserGender:
    enum:
    - female
    - male
    type: string
    x-enum-varnames:
    - GenderFemale
    - GenderMale
  models.UserResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.UserDetail'
        type: array
      paging:
        $ref: '#/definitions/models.PagingInfo'
    required:
    - data
    - paging
    type: object
  models.UserRole:
    enum:
    - user
    - admin
    type: string
    x-enum-varnames:
    - RoleUser
    - RoleAdmin
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is an online learning API server.
  termsOfService: http://swagger.io/terms/
  title: Online Learning API
  version: "1.0"
paths:
  /auth/forgot-password:
    post:
      consumes:
      - application/json
      description: Send a password reset link to the user's email
      parameters:
      - description: User email
        in: body
        name: email
        required: true
        schema:
          $ref: '#/definitions/models.ForgotPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
      summary: Request password reset
      tags:
      - Authentication
  /auth/login:
    post:
      consumes:
      - application/json
      description: Log in using email or username and password
      parameters:
      - description: Login credentials
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.Error'
      summary: Log in
      tags:
      - Authentication
  /auth/logout:
    post:
      description: Log out by clearing the refresh token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
      summary: Log out
      tags:
      - Authentication
  /auth/refresh-token:
    post:
      description: Refresh the access token using the refresh token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.AccessTokenResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.Error'
      summary: Refresh access token
      tags:
      - Authentication
  /auth/reset-password:
    post:
      consumes:
      - application/json
      description: Reset the user's password using a valid token
      parameters:
      - description: Reset token
        in: query
        name: token
        required: true
        type: string
      - description: New password
        in: body
        name: password
        required: true
        schema:
          $ref: '#/definitions/models.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.Error'
      summary: Reset user password
      tags:
      - Authentication
  /contact/:
    post:
      description: Send email contact
      parameters:
      - description: Send email
        in: body
        name: contact
        required: true
        schema:
          $ref: '#/definitions/models.Contact'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      summary: Send email contact
      tags:
      - Contact
  /documentations/:
    get:
      description: List of classes with their subjects and document counts
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ClassWithSubjects'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      security:
      - BearerAuth: []
      summary: List of classes with their subjects and document counts
      tags:
      - Documentation
  /documentations/upload:
    post:
      description: Upload document file
      parameters:
      - description: Subject ID
        in: formData
        name: subjectId
        required: true
        type: integer
      - description: Document title
        in: formData
        name: title
        required: true
        type: string
      - description: File to upload
        in: formData
        name: file
        required: true
        type: file
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.ClassWithSubjects'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      security:
      - BearerAuth: []
      summary: Upload document file
      tags:
      - Documentation
  /users/:
    get:
      description: Retrieve a list of all users, with optional filters for email,
        username, full name, date of birth, role, and pagination.
      parameters:
      - in: query
        name: dateOfBirth
        type: string
      - in: query
        name: email
        type: string
      - in: query
        name: fullName
        type: string
      - in: query
        maximum: 100
        minimum: 1
        name: limit
        type: integer
      - in: query
        minimum: 1
        name: page
        type: integer
      - in: query
        name: role
        type: string
      - in: query
        name: username
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      security:
      - BearerAuth: []
      summary: Get all users
      tags:
      - User
    post:
      consumes:
      - application/json
      description: Register a new user with email, username, and password
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.Error'
      summary: Register a new user
      tags:
      - User
  /users/{userId}:
    delete:
      description: Delete a user by user ID
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      security:
      - BearerAuth: []
      summary: Delete user
      tags:
      - User
    get:
      description: Retrieve user information by user ID
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserDetail'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      security:
      - BearerAuth: []
      summary: Get user by ID
      tags:
      - User
    put:
      consumes:
      - application/json
      description: Update user information by user ID
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserDetail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UpdateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      security:
      - BearerAuth: []
      summary: Update user information
      tags:
      - User
  /users/{userId}/avatar:
    put:
      consumes:
      - multipart/form-data
      description: Update the avatar for a specific user
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      - description: User Avatar
        in: formData
        name: avatar
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UpdateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.Error'
      security:
      - BearerAuth: []
      summary: Update user avatar
      tags:
      - User
  /users/{userId}/password:
    put:
      consumes:
      - application/json
      description: Change the user's password
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: integer
      - description: Password data
        in: body
        name: password
        required: true
        schema:
          $ref: '#/definitions/models.PasswordUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.Error'
      security:
      - BearerAuth: []
      summary: Change user password
      tags:
      - User
  /users/admin:
    post:
      consumes:
      - application/json
      description: Register a new user with email, username, and password
      parameters:
      - description: User data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Message'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.Error'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/models.Error'
      summary: Register a new user
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
